version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "packages/plasma-colors"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "packages/plasma-core"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "react"
        versions: ["^17"]
      - dependency-name: "react-dom"
        versions: ["^17"]
      - dependency-name: "@types/react"
        versions: ["^17"]
      - dependency-name: "@types/react-dom"
        versions: ["^17"]
      - dependency-name: "typescript"
        versions: ["^4"]
        # TODO: https://github.com/sberdevices/plasma/issues/714
      - dependency-name: "@types/styled-components"
        # TODO: https://github.com/sberdevices/plasma/issues/714
      - dependency-name: "@types/node"
        versions: ["^17"]

  - package-ecosystem: "npm"
    directory: "packages/plasma-icons"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "react"
        versions: ["^17"]
      - dependency-name: "react-dom"
        versions: ["^17"]
      - dependency-name: "@types/react"
        versions: ["^17"]
      - dependency-name: "@types/react-dom"
        versions: ["^17"]
      - dependency-name: "typescript"
        versions: ["^4"]

  - package-ecosystem: "npm"
    directory: "packages/plasma-tokens"
    schedule:
      interval: "daily"
    ignore:
        # TODO: https://github.com/sberdevices/plasma/issues/712
      - dependency-name: "style-dictionary"
        versions: ["3.x"]

  - package-ecosystem: "npm"
    directory: "packages/plasma-tokens-b2c"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "packages/plasma-tokens-web"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "packages/plasma-ui"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "react"
        versions: ["^17"]
      - dependency-name: "react-dom"
        versions: ["^17"]
      - dependency-name: "@types/react"
        versions: ["^17"]
      - dependency-name: "@types/react-dom"
        versions: ["^17"]
      - dependency-name: "typescript"
        versions: ["^4"]
        # TODO: https://github.com/sberdevices/plasma/issues/725
      - dependency-name: "jest"
        versions: ["^27"]
        # TODO: https://github.com/sberdevices/plasma/issues/725
      - dependency-name: "@types/jest"
        versions: ["^27"]
        # TODO: https://github.com/sberdevices/plasma/issues/726
      - dependency-name: "react-scripts"
        versions: ["^4"]
        # TODO: https://github.com/sberdevices/plasma/issues/727
      - dependency-name: "@types/styled-components"

  - package-ecosystem: "npm"
    directory: "packages/plasma-web"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "react"
        versions: ["^17"]
      - dependency-name: "react-dom"
        versions: ["^17"]
      - dependency-name: "@types/react"
        versions: ["^17"]
      - dependency-name: "@types/react-dom"
        versions: ["^17"]
      - dependency-name: "typescript"
        versions: ["^4"]
        # TODO: https://github.com/sberdevices/plasma/issues/726
      - dependency-name: "react-scripts"
        versions: ["^4"]
