/**
 * ToDo: ! Использовать данные иконки после https://github.com/sberdevices/plasma/issues/1058 в v2.0
 */
export { IconVideo } from './Icons/IconVideo';
export { IconAttentionCircle } from './Icons/IconAttentionCircle';
export { IconAntennaCircle } from './Icons/IconAntennaCircle';
export { IconBell } from './Icons/IconBell';
export { IconBuilding } from './Icons/IconBuilding';
export { IconArrowRightChevronRectangle } from './Icons/IconArrowRightChevronRectangle';
export { IconCircleCross } from './Icons/IconCircleCross';
export { IconMobile } from './Icons/IconMobile';
export { IconPhone } from './Icons/IconPhone';
export { IconSberPortal } from './Icons/IconSberPortal';
export { IconTVChannel } from './Icons/IconTVChannel';
export { IconEthernetOutline } from './Icons/IconEthernetOutline';
export { IconCableFill } from './Icons/IconCableFill';
export { IconCableOutline } from './Icons/IconCableOutline';
export { IconCableAlt2Fill } from './Icons/IconCableAlt2Fill';
export { IconAvTextOutline } from './Icons/IconAvTextOutline';
export { IconAvCableAlt1Fill } from './Icons/IconAvCableAlt1Fill';
export { IconAvCableAlt2Fill } from './Icons/IconAvCableAlt2Fill';
export { IconSberPortalFill } from './Icons/IconSberPortalFill';
export { IconTVChannelFill } from './Icons/IconTVChannelFill';
export { IconTV } from './Icons/IconTV';
export { IconTVFill } from './Icons/IconTVFill';
export { IconTVMode } from './Icons/IconTVMode';
export { IconTVWiFi } from './Icons/IconTVWiFi';
export { IconDevicesFill } from './Icons/IconDevicesFill';
export { IconPhoneFill } from './Icons/IconPhoneFill';
export { IconPhoneWiFi } from './Icons/IconPhoneWiFi';
export { IconMobileAutorotate } from './Icons/IconMobileAutorotate';
export { IconSberBoxTopFill } from './Icons/IconSberBoxTopFill';
export { IconSberBoxTop } from './Icons/IconSberBoxTop';
export { IconSberBoxTopFront } from './Icons/IconSberBoxTopFront';
export { IconCheckmarkOutline } from './Icons/IconCheckmarkOutline';
export { IconCutleryOutline } from './Icons/IconCutleryOutline';
export { IconBusOutline } from './Icons/IconBusOutline';
export { IconEllipseViewfinderOutline } from './Icons/IconEllipseViewfinderOutline';
export { IconBetaCircleOutline } from './Icons/IconBetaCircleOutline';
export { IconCouponOutline } from './Icons/IconCouponOutline';
export { IconCalendarOutline } from './Icons/IconCalendarOutline';
export { IconEarCrossOutline } from './Icons/IconEarCrossOutline';
export { IconBluetooth } from './Icons/IconBluetooth';
export { IconCloudCross } from './Icons/IconCloudCross';
export { IconCloseOutline } from './Icons/IconCloseOutline';
export { IconBalloonOutline } from './Icons/IconBalloonOutline';
export { IconCallBlock } from './Icons/IconCallBlock';
export { IconCall } from './Icons/IconCall';
export { IconCallOutgoingFill } from './Icons/IconCallOutgoingFill';
export { IconCallIncomingFill } from './Icons/IconCallIncomingFill';
export { IconCallMissedFill } from './Icons/IconCallMissedFill';
export { IconCallEndFill } from './Icons/IconCallEndFill';
export { IconBlock } from './Icons/IconBlock';
export { IconBluetoothOutline } from './Icons/IconBluetoothOutline';
export { IconSberBoxTime } from './Icons/IconSberBoxTime';
export { IconSberBoxTimeFill } from './Icons/IconSberBoxTimeFill';
export { IconDevicesSmarthome } from './Icons/IconDevicesSmarthome';
export { IconFaceAuth } from './Icons/IconFaceAuth';
export { IconAuthFingerprint } from './Icons/IconAuthFingerprint';

export { IconRoot } from './IconRoot';
export type { IconProps, IconSize } from './IconRoot';

export { Icon } from './Icon';
