export const typoTheme = {
    ':root': {
        '--plasma-typo-font-family': "'SB Sans Text', sans-serif",
        '--plasma-typo-body1-font-family': 'var(--plasma-typo-font-family)',
        '--plasma-typo-body1-font-weight': 500,
        '--plasma-typo-body1-font-style': 'normal',
        '--plasma-typo-body1-font-size': '1rem',
        '--plasma-typo-body1-letter-spacing': '-0.019em',
        '--plasma-typo-body1-line-height': '1.25rem',
        '--plasma-typo-button1-font-family': 'var(--plasma-typo-font-family)',
        '--plasma-typo-button1-font-weight': 600,
        '--plasma-typo-button1-font-style': 'normal',
        '--plasma-typo-button1-font-size': '1rem',
        '--plasma-typo-button1-letter-spacing': 'normal',
        '--plasma-typo-button1-line-height': '1.25rem',
        '--plasma-typo-button2-font-family': 'var(--plasma-typo-font-family)',
        '--plasma-typo-button2-font-weight': 600,
        '--plasma-typo-button2-font-style': 'normal',
        '--plasma-typo-button2-font-size': '0.875rem',
        '--plasma-typo-button2-letter-spacing': 'normal',
        '--plasma-typo-button2-line-height': '1rem',
        '--plasma-typo-caption-font-family': 'var(--plasma-typo-font-family)',
        '--plasma-typo-caption-font-weight': 500,
        '--plasma-typo-caption-font-style': 'normal',
        '--plasma-typo-caption-font-size': '0.75rem',
        '--plasma-typo-caption-letter-spacing': '-0.022em',
        '--plasma-typo-caption-line-height': '1rem',
        '--plasma-typo-footnote2-font-family': 'var(--plasma-typo-font-family)',
        '--plasma-typo-footnote2-font-weight': 600,
        '--plasma-typo-footnote2-font-style': 'normal',
        '--plasma-typo-footnote2-font-size': '0.875rem',
        '--plasma-typo-footnote2-letter-spacing': '-0.019em',
        '--plasma-typo-footnote2-line-height': '1.125rem',
    },
};
