/**
 * This code was generated by Diez version 10.6.0.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
import { Color, Font, GradientStop, LinearGradient, Point2D, Typograph } from '@diez/prefabs';

const sasUiKitColors = {
    textIconsPrimary: Color.rgba(8, 8, 8, 1),
    textIconsSecondary: Color.rgba(8, 8, 8, 0.5600000023841858),
    textIconsGblBlackSecondary: Color.rgba(8, 8, 8, 0.5600000023841858),
    textIconsSecondary1: Color.rgba(8, 8, 8, 0.5600000023841858),
    textIconsTertiary: Color.rgba(8, 8, 8, 0.2800000011920929),
    buttonsPrimary: Color.rgba(34, 106, 241, 1),
    textIconsCritical: Color.rgba(223, 38, 56, 1),
    buttonSecondaryDefault: Color.rgba(8, 8, 8, 0.05999999865889549),
    liquid50: Color.rgba(0, 0, 0, 0.3199999928474426),
    surface03: Color.rgba(8, 8, 8, 0.11999999731779099),
    textIconsWarning: Color.rgba(239, 107, 37, 1),
    textIconsSuccess: Color.rgba(9, 165, 82, 1),
    textIconsGblWhitePrimary: Color.rgba(255, 255, 255, 1),
    textIconsGblWhitePrimary1: Color.rgba(255, 255, 255, 0.9599999785423279),
    textIconsGblWhitePrimary2: Color.rgba(255, 255, 255, 0.9599999785423279),
    textIconsSecondary2: Color.rgba(8, 8, 8, 0.5600000023841858),
    buttonsPrimary1: Color.rgba(34, 106, 241, 1),
    textIconsGblBlackTetriary: Color.rgba(8, 8, 8, 0.2800000011920929),
    textIconsGblBlackSecondary1: Color.rgba(8, 8, 8, 0.5600000023841858),
    buttonsSpecialCritical: Color.rgba(223, 38, 56, 1),
    textIconsTetriary: Color.rgba(8, 8, 8, 0.2800000011920929),
    textIconsGblBalckSecondary: Color.rgba(8, 8, 8, 0.5600000023841858),
    surfaceGblGblWhite: Color.rgba(255, 255, 255, 1),
    liquid60: Color.rgba(255, 255, 255, 0.4699999988079071),
    liquid501: Color.rgba(255, 255, 255, 0.3199999928474426),
    textIconsPrimary1: Color.rgba(255, 255, 255, 0.9599999785423279),
    textIconsSecondary3: Color.rgba(255, 255, 255, 0.5600000023841858),
    textIconsSecondary4: Color.rgba(255, 255, 255, 0.5600000023841858),
    textIconsBrandSber: Color.rgba(42, 198, 115, 1),
    textIconsPrimary2: Color.rgba(255, 255, 255, 0.9599999785423279),
    surfaceLiquid03: Color.rgba(255, 255, 255, 0.20000000298023224),
    buttonsSecondary: Color.rgba(0, 0, 0, 0.05000000074505806),
    brandNew: Color.rgba(34, 106, 241, 1),
};

const sasUiKitGradients = {
    gradientGreenBlue: new LinearGradient({
        stops: [GradientStop.make(0, Color.rgba(32, 218, 3, 1)), GradientStop.make(1, Color.rgba(17, 221, 255, 1))],
        start: Point2D.make(-0.181831427364076, 3.053300401633283),
        end: Point2D.make(0.661955274374661, -0.83389703953045),
    }),
};

const sasUiKitTypography = {
    '4044Headline1': new Typograph({
        letterSpacing: -0.8,
        fontSize: 40,
        lineHeight: 44,
        color: Color.rgba(8, 8, 8, 1),
        font: new Font({ name: 'SBSansText-Semibold' }),
    }),
    '3236Headline2': new Typograph({
        letterSpacing: -0.35200000762939454,
        fontSize: 32,
        lineHeight: 36,
        color: Color.rgba(8, 8, 8, 1),
        font: new Font({ name: 'SBSansText-Semibold' }),
    }),
    '2428Headline3': new Typograph({
        letterSpacing: -0.5280000114440918,
        fontSize: 24,
        lineHeight: 28,
        color: Color.rgba(8, 8, 8, 1),
        font: new Font({ name: 'SBSansText-Semibold' }),
    }),
    '2024Headline4': new Typograph({
        letterSpacing: -0.5,
        fontSize: 20,
        lineHeight: 24,
        color: Color.rgba(8, 8, 8, 1),
        font: new Font({ name: 'SBSansText-Semibold' }),
    }),
    '2024Subtittle': new Typograph({
        letterSpacing: -0.3799999952316285,
        fontSize: 20,
        lineHeight: 24,
        color: Color.rgba(8, 8, 8, 1),
        font: new Font({ name: 'SBSansText-Regular' }),
    }),
    '1620Headline5': new Typograph({
        letterSpacing: -0.30399999618530277,
        fontSize: 16,
        lineHeight: 20,
        color: Color.rgba(8, 8, 8, 1),
        font: new Font({ name: 'SBSansText-Semibold' }),
    }),
    '1620Body1': new Typograph({
        letterSpacing: -0.30399999618530277,
        fontSize: 16,
        lineHeight: 20,
        color: Color.rgba(8, 8, 8, 1),
        font: new Font({ name: 'SBSansText-Regular' }),
    }),
    '1624ParagraphText1': new Typograph({
        letterSpacing: -0.30399999618530277,
        fontSize: 16,
        lineHeight: 24,
        color: Color.rgba(8, 8, 8, 1),
        font: new Font({ name: 'SBSansText-Regular' }),
    }),
    '1418Footnote1': new Typograph({
        letterSpacing: -0.2659999966621399,
        fontSize: 14,
        lineHeight: 18,
        color: Color.rgba(8, 8, 8, 1),
        font: new Font({ name: 'SBSansText-Medium' }),
    }),
    '1418Footnote2': new Typograph({
        letterSpacing: -0.2659999966621399,
        fontSize: 14,
        lineHeight: 18,
        color: Color.rgba(8, 8, 8, 1),
        font: new Font({ name: 'SBSansText-Semibold' }),
    }),
    '1620Button1': new Typograph({
        letterSpacing: 0,
        fontSize: 16,
        lineHeight: 20,
        color: Color.rgba(8, 8, 8, 1),
        font: new Font({ name: 'SBSansText-Semibold' }),
    }),
    '1416Button2': new Typograph({
        letterSpacing: 0,
        fontSize: 14,
        lineHeight: 16,
        color: Color.rgba(8, 8, 8, 1),
        font: new Font({ name: 'SBSansText-Semibold' }),
    }),
    '1216Caption': new Typograph({
        letterSpacing: -0.2640000057220459,
        fontSize: 12,
        lineHeight: 16,
        color: Color.rgba(0, 0, 0, 1),
        font: new Font({ name: 'SBSansText-Medium' }),
    }),
    '1012Underline': new Typograph({
        letterSpacing: 0.125,
        fontSize: 10,
        lineHeight: 12,
        color: Color.rgba(8, 8, 8, 1),
        font: new Font({ name: 'SBSansText-Medium' }),
    }),
};

export const sasUiKitTokens = {
    colors: sasUiKitColors,
    gradients: sasUiKitGradients,
    typography: sasUiKitTypography,
};
