const { DESIGN_SYSTEM_PREFIX: designSystemPrefix, ROBO_COMMENT: roboComment } = process.env;

export const DESIGN_SYSTEM_PREFIX = designSystemPrefix !== undefined ? designSystemPrefix : 'plasma';
export const ROBO_COMMENT =
    roboComment !== undefined ? roboComment : '// Generated by robots, do not change this manually!\n\n';
export const DEPRECATED_COMMENT = '// @deprecated';
export const HTML_FONT_SIZE = 16;
