name: Versionate documentation
description: Reads commit log and makes docs version if needed.
inputs:
  token:
    description: The GitHub token used to create an authenticated client.
    required: true
outputs:
  result:
    description: Process done with success.
runs:
  using: node12
  main: 'lib/main.js'
branding:
  icon: check-square
  color: purple
