import React from 'react';
import styled from 'styled-components';
import { IconClose, IconDownload, IconHeartStroke, IconMinus, IconPlus } from '@sberdevices/plasma-icons';
import { critical, surfaceLiquid01, SpacingProps } from '@sberdevices/plasma-core';
import {
    ActionButton,
    Badge,
    Body1,
    Body2,
    Body3,
    Button,
    Button1,
    Button2,
    Caption,
    Card,
    CardBody,
    CardContent,
    CardMedia,
    CardHeadline1,
    CardParagraph1,
    Cell,
    CellIcon,
    CellListItem,
    CellDisclosure,
    Container,
    Col,
    Display1,
    Display2,
    Display3,
    Footnote1,
    Footnote2,
    Header,
    HeaderBack,
    HeaderContent,
    HeaderLogo,
    HeaderRoot,
    HeaderSubtitle,
    HeaderTitle,
    HeaderTitleWrapper,
    Headline1,
    Headline2,
    Headline3,
    Headline4,
    LineSkeleton,
    PaginationDots,
    PaginationDot,
    ParagraphText1,
    ParagraphText2,
    RectSkeleton,
    Row,
    SmartPaginationDots,
    Stepper,
    StepperButton,
    StepperRoot,
    StepperValue,
    Tabs,
    TabItem,
    TextArea,
    TextBox,
    TextBoxTitle,
    TextBoxSubTitle,
    TextBoxBiggerTitle,
    TextBoxBigTitle,
    TextField,
    TextSkeleton,
    Underline,
    applySpacing,
    withSkeleton,
} from '@sberdevices/plasma-ui';

const Filler = styled.div<SpacingProps>`
    ${applySpacing}

    display: flex;
    align-items: center;
    justify-content: center;

    box-sizing: border-box;

    width: 100%;
    padding: 0.5rem 1rem;

    background-color: ${surfaceLiquid01};
`;

// Add react-live imports you need here
const ReactLiveScope = {
    React,
    ActionButton,
    Badge,
    Body1,
    Body2,
    Body3,
    Button,
    Button1,
    Button2,
    Caption,
    Card,
    CardBody,
    CardContent,
    CardMedia,
    CardHeadline1,
    CardParagraph1,
    Cell,
    CellIcon,
    CellListItem,
    CellDisclosure,
    Container,
    Col,
    Display1,
    Display2,
    Display3,
    Filler,
    Footnote1,
    Footnote2,
    Header,
    HeaderBack,
    HeaderContent,
    HeaderLogo,
    HeaderRoot,
    HeaderSubtitle,
    HeaderTitle,
    HeaderTitleWrapper,
    Headline1,
    Headline2,
    Headline3,
    Headline4,
    IconClose,
    IconDownload,
    IconHeartStroke,
    IconMinus,
    IconPlus,
    LineSkeleton,
    PaginationDots,
    PaginationDot,
    ParagraphText1,
    ParagraphText2,
    RectSkeleton,
    Row,
    SmartPaginationDots,
    Stepper,
    StepperButton,
    StepperRoot,
    StepperValue,
    Tabs,
    TabItem,
    TextArea,
    TextBox,
    TextBoxTitle,
    TextBoxSubTitle,
    TextBoxBiggerTitle,
    TextBoxBigTitle,
    TextField,
    TextSkeleton,
    Underline,
    withSkeleton,
    critical,
    ...React,
};

export default ReactLiveScope;
