name: PR ad-sdk demo

on:
  push:
    branches:
      - master

jobs:
  ad-beta:
    name: Build
    runs-on: ubuntu-latest
    env:
      NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-deps-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-deps-${{ hashFiles('package-lock.json') }}
      - name: Setup ad-sdk
        run: |
          npm i
          npx lerna bootstrap --scope="@sberdevices/ad-sdk"
          npm i --prefix="./packages/ad-sdk/examples/demo"
      - name: Build ad-sdk
        run: |
          npm run prepare-demo --prefix="./packages/ad-sdk"
          npm run build:demo --prefix="./packages/ad-sdk/examples/demo"
          mkdir -p ../build
          cp -R ./packages/ad-sdk/examples/demo/public ../build/ad-sdk-next

      - name: Upload ad-sdk build
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.SB_HOST }}
          username: ${{ secrets.SB_LOGIN }}
          privateKey: ${{ secrets.SB_KEY }}
          local: "../build"
          remote: "/var/www/plasma"

      - name: Update and clean ad-sdk
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SB_HOST }}
          username: ${{ secrets.SB_LOGIN }}
          key: ${{ secrets.SB_KEY }}
          script: |
            cd ../../var/www/plasma
            rm -rf ad-sdk/
            mv ad-sdk-next ad-sdk
