name: Main Documentation and Storybook

on:
  push:
    branches:
      - rc
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-deps-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-deps-${{ hashFiles('package-lock.json') }}

      - name: Setup packages
        run: |
          npm i
          npx lerna bootstrap

      - name: Lint
        run: npm run lint

      - name: Prepare directory
        run: mkdir ../build

      - name: Plasma UI Storybook
        run: |
          npm run storybook:build --prefix="./packages/plasma-ui"

      - name: Plasma Web Storybook
        run: |
          npm run storybook:build --prefix="./packages/plasma-web"
      
      - name: Extract docgenInfo from Storybook
        run: npm run extract-docgen-info

      - name: Documentation App
        run: |
          npm run build --prefix="./docs"
      
      - name: Copy builds
        run: |
          cp -R ./docs/build ../build/next
          cp -R ./packages/plasma-ui/build-sb ../build/next/ui-storybook
          cp -R ./packages/plasma-web/build-sb ../build/next/web-storybook

      - name: Upload documentation build
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.DOCS_HOST }}
          username: ${{ secrets.DOCS_LOGIN }}
          privateKey: ${{ secrets.DOCS_KEY }}
          local: "../build"
          remote: "/var/www/plasma"

      - name: Update and clean documentation
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOCS_HOST }}
          username: ${{ secrets.DOCS_LOGIN }}
          key: ${{ secrets.DOCS_KEY }}
          script: |
            cd ../../var/www/plasma
            rm -rf current/
            mv next current
