name: Cypress component testing

on: push

jobs:
  cypress:
    runs-on: ubuntu-latest
    env:
      NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
      COVERAGE: true
    steps: 
    - uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Setup packages
      run: |
        npm i
        npx lerna bootstrap

    - name: Run Typescript Coverage
      if: ${{ always() }}
      run: |
        npm run typescript-coverage
